# Generated by Django 3.2.16 on 2022-12-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('seconds_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('sleep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='portal.sleepsession')),
            ],
            options={
                'verbose_name': 'Audio File',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='SnoringEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_seconds_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('end_seconds_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sleep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snoring_episode', to='portal.sleepsession')),
            ],
            options={
                'verbose_name': 'Snoring Episode',
            },
        ),
        migrations.CreateModel(
            name='PositionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('seconds_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position', models.CharField(blank=True, choices=[('Supine', 'Supine'), ('Prone', 'Prone'), ('Left', 'Left'), ('Right', 'Right'), ('Standing', 'Standing'), ('Other', 'Other')], max_length=8)),
                ('sleep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_events', to='portal.sleepsession')),
            ],
            options={
                'verbose_name': 'Position',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='AudioLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_elapsed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('label_1', models.CharField(max_length=50)),
                ('label_2', models.CharField(max_length=50)),
                ('label_3', models.CharField(max_length=50)),
                ('score_1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_3', models.DecimalField(decimal_places=3, max_digits=5)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_labels', to='data.audiofile')),
            ],
            options={
                'verbose_name': 'Audio Label',
            },
        ),
    ]
