# Generated by Django 3.2.16 on 2022-11-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsessionaudio',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
