# Generated by Django 3.2.16 on 2023-02-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionevent',
            options={'ordering': ('-pk',), 'verbose_name': 'Position Event'},
        ),
        migrations.AlterField(
            model_name='audiolabel',
            name='audio_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='data.audiofile'),
        ),
    ]
