# Generated by Django 3.2.16 on 2022-11-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_sleepsession_true_start_time'),
        ('data', '0002_alter_sleepsessionaudio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsessionaudio',
            name='sleep_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_session_audio', to='portal.sleepsession'),
        ),
        migrations.CreateModel(
            name='SnoringEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sleep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snoring_episode', to='portal.sleepsession')),
            ],
            options={
                'verbose_name': 'SnoringEpisode',
            },
        ),
    ]
