# Generated by Django 3.2.16 on 2022-11-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20221107_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepsessionaudio',
            options={'ordering': ('-pk',), 'verbose_name': 'Sleep Session Audio Files'},
        ),
        migrations.AlterModelOptions(
            name='snoringepisode',
            options={'verbose_name': 'Snoring Episodes'},
        ),
    ]
