# Generated by Django 3.2.16 on 2022-11-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_sleepsession_true_start_time'),
        ('data', '0004_auto_20221107_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('z', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.CharField(blank=True, choices=[('Supine', 'Supine'), ('Prone', 'Prone'), ('Left', 'Left'), ('Right', 'Right'), ('Standing', 'Standing'), ('Other', 'Other')], max_length=8)),
                ('sleep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portal.sleepsession')),
            ],
            options={
                'verbose_name': 'Position',
                'ordering': ('-pk',),
            },
        ),
    ]
