# Generated by Django 3.2.16 on 2022-11-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepsessionaudio',
            options={'ordering': ('-pk',), 'verbose_name': 'Sleep Session Audio File'},
        ),
        migrations.AlterModelOptions(
            name='snoringepisode',
            options={'verbose_name': 'Snoring Episode'},
        ),
    ]
