# Generated by Django 3.2.16 on 2022-11-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_sleepsession_collection_period'),
        ('data', '0007_auto_20221117_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsessionaudio',
            name='sleep_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='portal.sleepsession'),
        ),
        migrations.CreateModel(
            name='AudioLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label_1', models.CharField(max_length=50)),
                ('label_2', models.CharField(max_length=50)),
                ('label_3', models.CharField(max_length=50)),
                ('score_1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_3', models.DecimalField(decimal_places=3, max_digits=5)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='data.sleepsessionaudio')),
            ],
            options={
                'verbose_name': 'Audio Label',
            },
        ),
    ]
