# Generated by Django 3.2.16 on 2022-12-01 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Collection Period',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_start_time', models.DateTimeField()),
                ('device_end_time', models.DateTimeField()),
                ('true_start_time', models.DateTimeField(blank=True, null=True)),
                ('collection_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to='portal.collectionperiod')),
            ],
            options={
                'verbose_name': 'Sleep Session',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='collectionperiod',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='portal.patient'),
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinician',
            },
        ),
    ]
