# Generated by Django 3.2.16 on 2022-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collectionperiod',
            name='start_date',
            field=models.DateField(),
        ),
    ]
