# Generated by Django 3.2.16 on 2022-11-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20221105_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinician',
            options={'verbose_name': 'Clinician'},
        ),
    ]
