# Generated by Django 3.2.16 on 2022-11-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_clinician_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionperiod',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='portal.patient'),
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('true_start_time', models.DateTimeField()),
                ('collection_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_period', to='portal.collectionperiod')),
            ],
            options={
                'verbose_name': 'Sleep Session',
                'ordering': ('-pk',),
            },
        ),
    ]
