# Generated by Django 3.2.16 on 2022-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20221105_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsession',
            name='true_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
