# Generated by Django 3.2.16 on 2022-11-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_sleepsession_true_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsession',
            name='collection_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to='portal.collectionperiod'),
        ),
    ]
